### PR TITLE
Add glide support as separate library

### PR DESCRIPTION
**Pull request by mifmasterz**
- the new component like datagrid, list/combobox, slider were added in glide library
- somechanges in UI library : add ID in ui element, add passwordbox parameter in textbox control
- add xml library

### CODE REVIEW

**Comment by gus-ghielec** [comment]
This PR still touched files (and has conflict) outside `GHIElectronics.TinyCLR.Glide`. It is making changes to Drawing and UI. Glide must be a separate library (NuGet) and it should not modify anything externally or include any other libraries.

**Comment by gus-ghielec** [comment]
XML, and any other libraries, should not be included in this PR. We have XML now added as its own library.

**Comment by Palomino34** [comment]
Telll us why did you add [assembly: InternalsVisibleTo("GHIElectronics.TinyCLR.Glide")] into GHIElectronics.TinyCLR.Drawing ?

To access some internal or private properties? Can you use reflection?

**Comment by Palomino34** [comment]
For adding "ID" to UIElement.cs, please inherit from UIElement and add 'ID' in your class.

**Comment by mifmasterz** [comment]
> Telll us why did you add [assembly: InternalsVisibleTo("GHIElectronics.TinyCLR.Glide")] into GHIElectronics.TinyCLR.Drawing ?
> 
> To access some internal or private properties? Can you use reflection?

I have tried to use reflection, yes it can run, but it's really slow, and sometimes we have got out of memory exception, please take a look code below, I think this is too much use of reflection...


using System;
using System.Drawing;
using System.Reflection;

namespace GHIElectronics.TinyCLR.UI.Glide {
    public class BitmapHelper : IDisposable {
        public readonly Graphics g;
        private readonly object surface; //System.Drawing.Internal.Bitmap
        public const ushort OpacityOpaque = 255;
        public const ushort OpacityTransparent = 0;
        public const uint DT_WordWrap = 1;
        public const uint DT_TruncateAtBottom = 4;
        public const uint DT_IgnoreHeight = 16;
        public const uint DT_AlignmentLeft = 0;
        public const uint DT_AlignmentCenter = 2;
        public const uint DT_AlignmentRight = 32;
        public const uint DT_TrimmingWordEllipsis = 8;
        public const uint DT_TrimmingCharacterEllipsis = 64;
        public static object CallMethod(object o, string methodName, params object[] args) {
            var mi = o.GetType().GetMethod(methodName, System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            if (mi != null) {
                return mi.Invoke(o, args);
            }
            return null;
        }
        public int Height {
            get {
                //return this.g.Height;
                var myType = typeof(Graphics);
                var myField = myType.GetField("Height",
                BindingFlags.NonPublic | BindingFlags.Instance);
                return (int)myField.GetValue(this.g);
            }
        }

        public int Width {
            get {
                //return this.g.Width;
                var myType = typeof(Graphics);
                var myField = myType.GetField("Width",
                BindingFlags.NonPublic | BindingFlags.Instance);
                return (int)myField.GetValue(this.g);
            }
        }

        public BitmapHelper(Graphics g) {
            this.g = g;
            this.surface = BitmapHelper.Extract(g);

        }

        private static object Extract(Graphics g) {
            var graphicType = typeof(Graphics);
            var surfaceField = graphicType.GetField("surface",
            BindingFlags.NonPublic | BindingFlags.Instance);
            return surfaceField.GetValue(g);
            /*
            if (g.surface is System.Drawing.Internal.Bitmap surface)
                return surface;
            */
            throw new NotSupportedException();
        }

        public void Dispose() {
            //this.g.Dispose();
            CallMethod(this.g, "Dispose", null);
        }

        public void Clear() {
            //this.g.Clear();//System.Drawing.Color.Black
            CallMethod(this.g, "Clear", null);
        }

        public void Flush(int x, int y, int width, int height) {
            //this.g.Flush();
            CallMethod(this.g, "Flush", null);
        }

        internal void SetPixel(int x, int y, Media.Color color) {
            //this.surface.SetPixel(x, y, color.ToNativeColor());
            CallMethod(this.surface, "SetPixel", x, y, color.ToNativeColor());
        }

        internal void SetClippingRectangle(int x, int y, int width, int height) {
            //this.surface.SetClippingRectangle(x, y, width, height);
            CallMethod(this.surface, "SetClippingRectangle", x, y, width, height);
        }

        internal void DrawEllipse(
          Media.Color color1,
          ushort thickness,
          int v1,
          int v2,
          int xRadius,
          int yRadius,
          Media.Color color2,
          int v3,
          int v4,
          Media.Color color3,
          int v5,
          int v6,
          ushort v7) {
            //this.surface.DrawEllipse(color1.ToNativeColor(), (int)thickness, v1, v2, xRadius, yRadius, color2.ToNativeColor(), v3, v4, color3.ToNativeColor(), v5, v6, v7);
            CallMethod(this.surface, "DrawEllipse", color1.ToNativeColor(), (int)thickness, v1, v2, xRadius, yRadius, color2.ToNativeColor(), v3, v4, color3.ToNativeColor(), v5, v6, v7);
        }

        internal void DrawRectangle(
          Media.Color outlineColor,
          ushort outlineThickness,
          int x,
          int y,
          int width,
          int height,
          int v1,
          int v2,
          Media.Color color1,
          int v3,
          int v4,
          Media.Color color2,
          int v5,
          int v6,
          ushort opacity) {
            //this.surface.DrawRectangle(outlineColor.ToNativeColor(), (int)outlineThickness, x, y, width, height, v1, v2, color1.ToNativeColor(), v3, v4, color2.ToNativeColor(), v5, v6, opacity);
            CallMethod(this.surface, "DrawRectangle", outlineColor.ToNativeColor(), (int)outlineThickness, x, y, width, height, v1, v2, color1.ToNativeColor(), v3, v4, color2.ToNativeColor(), v5, v6, opacity);
        }

        internal void DrawImage(
          int v1,
          int v2,
          System.Drawing.Bitmap source,
          int v3,
          int v4,
          int width,
          int height) {
            //this.surface.DrawImage(v1, v2, BitmapHelper.Extract(source.data), v3, v4, width, height, (ushort)byte.MaxValue);
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(source);
            CallMethod(this.surface, "DrawImage", v1, v2, BitmapHelper.Extract(gx), v3, v4, width, height, (ushort)byte.MaxValue);
        }

        internal void DrawImage(
          int x,
          int y,
          System.Drawing.Bitmap bitmapSource,
          int v1,
          int v2,
          int width,
          int height,
          ushort opacity) {
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(bitmapSource);
            //this.surface.DrawImage(x, y, BitmapHelper.Extract(bitmapSource.data), v1, v2, width, height, opacity);
            CallMethod(this.surface, "DrawImage", x, y, BitmapHelper.Extract(gx), v1, v2, width, height, opacity);
        }

        internal void DrawLine(Media.Color color, int v, int ix1, int y1, int ix2, int y2) {
            //this.surface.DrawLine(color.ToNativeColor(), v, ix1, y1, ix2, y2);
            CallMethod(this.surface, "DrawLine", color.ToNativeColor(), v, ix1, y1, ix2, y2);
        }

        internal void DrawText(string text, Font font, Media.Color color, int v1, int v2) {
            //this.surface.DrawText(text, font, color.ToNativeColor(), v1, v2);
            CallMethod(this.surface, "DrawText", text, font, color.ToNativeColor(), v1, v2);
        }

        internal bool DrawTextInRect(
          ref string text,
          ref int xRelStart,
          ref int yRelStart,
          int v1,
          int v2,
          int width,
          int height,
          uint flags,
          Media.Color color,
          Font font) {
            //return this.surface.DrawTextInRect(ref text, ref xRelStart, ref yRelStart, v1, v2, width, height, flags, color.ToNativeColor(), font);
            var pars = new object[] { text, xRelStart, yRelStart, v1, v2, width, height, flags, color.ToNativeColor(), font };
            var obj = CallMethod(this.surface, "DrawTextInRect", pars);
            return (bool)obj;
        }

        internal void TileImage(
          int v1,
          int v2,
          System.Drawing.Bitmap bitmap,
          int width,
          int height,
          ushort opacity) {
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(bitmap);
            //this.surface.TileImage(v1, v2, BitmapHelper.Extract(bitmap.data), width, height, opacity);
            CallMethod(this.surface, "TileImage", v1, v2, BitmapHelper.Extract(gx), width, height, opacity);
        }

        internal void RotateImage(
          int angle,
          int v1,
          int v2,
          System.Drawing.Bitmap bitmap,
          int sourceX,
          int sourceY,
          int sourceWidth,
          int sourceHeight,
          ushort opacity) {
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(bitmap);
            //this.surface.RotateImage(angle, v1, v2, BitmapHelper.Extract(bitmap.data), sourceX, sourceY, sourceWidth, sourceHeight, opacity);
            CallMethod(this.surface, "RotateImage", angle, v1, v2, BitmapHelper.Extract(gx), sourceX, sourceY, sourceWidth, sourceHeight, opacity);
        }

        internal void StretchImage(
          int x,
          int y,
          System.Drawing.Bitmap bitmapSource,
          int width,
          int height,
          ushort opacity) {
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(bitmapSource);
            //this.surface.StretchImage(x, y, BitmapHelper.Extract(bitmapSource.data), width, height, opacity);
            CallMethod(this.surface, "StretchImage", x, y, BitmapHelper.Extract(gx), width, height, opacity);
        }

        internal void StretchImage(
          int v1,
          int v2,
          int widthDst,
          int heightDst,
          System.Drawing.Bitmap bitmap,
          int xSrc,
          int ySrc,
          int widthSrc,
          int heightSrc,
          ushort opacity) {
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(bitmap);
            //this.surface.StretchImage(v1, v2, widthDst, heightDst, bitmap.data.surface, xSrc, ySrc, widthSrc, heightSrc, opacity);
            CallMethod(this.surface, "StretchImage", v1, v2, widthDst, heightDst, BitmapHelper.Extract(gx), xSrc, ySrc, widthSrc, heightSrc, opacity);
        }

        public void Scale9Image(
          int v1,
          int v2,
          int widthDst,
          int heightDst,
          System.Drawing.Bitmap bitmap,
          int leftBorder,
          int topBorder,
          int rightBorder,
          int bottomBorder,
          ushort opacity) {
            var myType = typeof(Image);
            var myField = myType.GetField("data",
            BindingFlags.NonPublic | BindingFlags.Instance);

            var gx = (Graphics)myField.GetValue(bitmap);
            //this.surface.Scale9Image(v1, v2, widthDst, heightDst, BitmapHelper.Extract(bitmap.data), leftBorder, topBorder, rightBorder, bottomBorder, opacity);
            CallMethod(this.surface, "Scale9Image", v1, v2, widthDst, heightDst, BitmapHelper.Extract(gx), leftBorder, topBorder, rightBorder, bottomBorder, opacity);
        }
    }
}

**Comment by Palomino34** [comment]
In near feature, we will change those Bitmap Api to public so no need reflection. But for now, we need reflection to make sure Glide work and no need to changes any other exist assemblies. So slow is fine for now, I think.

For memory issue, can you enable external memory as main heap to see.

You can zip your test demo (Program.cs) so we can help to test.

**Comment by Palomino34** [comment]
Wair for us to rework on graphics then you don't need to do reflection.

**Comment by Palomino34** [comment]
We confirm that Glide work fine with TinyCLR OS2 rc2.

But we are not going to add Glide to TinyCLR Library. So close this PR for now.

**Pull request closed without merging**
