### PR TITLE
Adding a few 'ease of use' tweaks to the library.

### PR DESCRIPTION
**Pull request by axa88**
Gpio.cs
What: Add Toggle Method.
Why: Reduce boiler plate code when toggling a port

Timeout.cs
What: Add InfiniteTimeSpan.
Why: Allows use of Timer.Change method with Timespan overload

mscorlib/Debug
What: Add Write Method.
Why: There is no current way to write to debug without adding a a carriage return/line feed

### CODE REVIEW

**Comment by Palomino34** [comment]
We made a branch to_v2.2.0. Could you please make PR to this branch?

What you added may change checksum or effect to other customers.

**Comment by axa88** [comment]
> We made a branch to_v2.2.0. Could you please make PR to this branch?
> 
> What you added may change checksum or effect to other customers.

@Palomino34 
im sorry, ive been poking around and still have no idea how to move to the new branch.

**Comment by axa88** [comment]
@Palomino34 
Sorry, could you instruct me exactly what i need to do to help get this modification applied?

**Comment by axa88** [comment]
trying to satisfy PR requirement

**Pull request closed without merging**
