### PR TITLE
add glide library

### PR DESCRIPTION
**Pull request by mifmasterz**
-use the existing xml library
-remove ID prop from uielement and refactored glide library
-add password masking feature for textbox (with IsPasswordBox property)

Note:
-How to get internal class with reflection ? in order to use some method in System.Drawing.Internal.Bitmap

### CODE REVIEW

**Comment by Palomino34** [comment]
Wair for us to rework on graphics then you don't need to do reflection.

**Comment by mifmasterz** [comment]
> Wair for us to rework on graphics then you don't need to do reflection.

Ok I'll wait, let me know if it's ready ;D

**Comment by Palomino34** [comment]
We confirm that your Glide work fine with TinyCLR OS2 rc2.

But we are not going to add Glide to TinyCLR Library. So close this PR for now.

**Comment by mifmasterz** [comment]
ok, glad to hear that. congratulations for the RC 2 release

**Pull request closed without merging**
